-- MySQL Script generated by MySQL Workbench
-- 10/23/15 15:30:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_mvc4php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mvc4php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mvc4php` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_mvc4php` ;

-- -----------------------------------------------------
-- Table `db_mvc4php`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mvc4php`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `firma` VARCHAR(45) NULL COMMENT '',
  `firstname` VARCHAR(45) NULL COMMENT '',
  `lastname` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `contact` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mvc4php`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mvc4php`.`Contract` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `package` VARCHAR(45) NULL COMMENT '',
  `service` VARCHAR(45) NULL COMMENT '',
  `price` VARCHAR(45) NULL COMMENT '',
  `fk_customer` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Contract_Customer_idx` (`fk_customer` ASC)  COMMENT '',
  CONSTRAINT `fk_Contract_Customer`
    FOREIGN KEY (`fk_customer`)
    REFERENCES `db_mvc4php`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;